import type {
  ActivityLog,
  AgentDefinition,
  AgentRun,
  AgentKey,
  ComplianceReview,
  Lead,
  LeadStatus,
  OutreachMessage,
  Reply,
  Settings,
  Task,
  WebsiteProject,
} from "@/lib/types";

export const leadStatuses: LeadStatus[] = [
  "New",
  "Scored",
  "Outreach Ready",
  "Outreach Sent",
  "Replied",
  "Interested",
  "Owner Talking",
  "Send to Website Team",
  "Website In Progress",
  "QA Review",
  "Compliance Review",
  "Client Preview Ready",
  "Revision Requested",
  "Closed Won",
  "Closed Lost",
];

export const workflowStages = [
  { name: "Lead Capture", statuses: ["New", "Scored"] as LeadStatus[] },
  { name: "Automated Outreach", statuses: ["Outreach Ready", "Outreach Sent", "Replied"] as LeadStatus[] },
  { name: "Owner Conversation", statuses: ["Interested", "Owner Talking", "Send to Website Team"] as LeadStatus[] },
  { name: "Website Team", statuses: ["Website In Progress", "QA Review", "Compliance Review"] as LeadStatus[] },
  { name: "Delivery", statuses: ["Client Preview Ready", "Revision Requested", "Closed Won", "Closed Lost"] as LeadStatus[] },
];

export const agentDefinitions: AgentDefinition[] = [
  {
    key: "lead-finder",
    name: "Lead Finder Agent",
    purpose: "Finds or imports businesses likely to need a higher-converting website.",
    status: "Complete",
    model: "gpt-4.1-mini",
    lastRun: "2026-06-24T13:05:00.000Z",
    successRate: 91,
    avgDuration: "1m 18s",
    outputLabel: "lead batches",
  },
  {
    key: "lead-scoring",
    name: "Lead Scoring Agent",
    purpose: "Scores weak websites, mobile issues, SEO gaps, brand quality, speed, and buy intent.",
    status: "Running",
    model: "gpt-4.1-mini",
    lastRun: "2026-06-24T16:32:00.000Z",
    successRate: 94,
    avgDuration: "42s",
    outputLabel: "scorecards",
  },
  {
    key: "marketing-strategy",
    name: "Marketing Strategy Agent",
    purpose: "Creates offer angles, pain points, package recommendations, and pricing bands.",
    status: "Complete",
    model: "gpt-4.1",
    lastRun: "2026-06-24T15:55:00.000Z",
    successRate: 89,
    avgDuration: "58s",
    outputLabel: "strategy briefs",
  },
  {
    key: "outreach",
    name: "Outreach Agent",
    purpose: "Generates compliant email, SMS, follow-up, and short DM drafts.",
    status: "Needs Review",
    model: "gpt-4.1-mini",
    lastRun: "2026-06-24T16:10:00.000Z",
    successRate: 87,
    avgDuration: "36s",
    outputLabel: "message sets",
  },
  {
    key: "reply-classifier",
    name: "Reply Classifier Agent",
    purpose: "Classifies replies as interested, not interested, call requested, wrong contact, or do not contact.",
    status: "Complete",
    model: "gpt-4.1-mini",
    lastRun: "2026-06-24T14:28:00.000Z",
    successRate: 96,
    avgDuration: "11s",
    outputLabel: "reply labels",
  },
  {
    key: "website-intake",
    name: "Website Intake Agent",
    purpose: "Turns owner notes into page requirements, style direction, CTAs, and missing-info checklists.",
    status: "Idle",
    model: "gpt-4.1",
    lastRun: "2026-06-23T18:04:00.000Z",
    successRate: 92,
    avgDuration: "49s",
    outputLabel: "intake plans",
  },
  {
    key: "website-builder-1",
    name: "Website Builder Agent 1",
    purpose: "Creates homepage structure, conversion copy, section sequencing, hero concepts, and service cards.",
    status: "Running",
    model: "gpt-4.1",
    lastRun: "2026-06-24T16:45:00.000Z",
    successRate: 88,
    avgDuration: "2m 04s",
    outputLabel: "home drafts",
  },
  {
    key: "website-builder-2",
    name: "Website Builder Agent 2",
    purpose: "Creates full page drafts for About, Services, Contact, FAQ, landing pages, and local SEO content.",
    status: "Running",
    model: "gpt-4.1",
    lastRun: "2026-06-24T16:46:00.000Z",
    successRate: 86,
    avgDuration: "2m 41s",
    outputLabel: "page drafts",
  },
  {
    key: "qa",
    name: "QA Agent",
    purpose: "Checks spelling, grammar, links, CTAs, mobile layout, consistency, forms, speed, and accessibility basics.",
    status: "Complete",
    model: "gpt-4.1-mini",
    lastRun: "2026-06-24T12:42:00.000Z",
    successRate: 93,
    avgDuration: "1m 01s",
    outputLabel: "QA reports",
  },
  {
    key: "security-compliance",
    name: "Security & Compliance Agent",
    purpose: "Blocks high-risk outreach or website delivery until sender identity, unsubscribe, claims, privacy, CASL/PIPEDA, and form-security issues are fixed.",
    status: "Blocked",
    model: "gpt-4.1",
    lastRun: "2026-06-24T16:20:00.000Z",
    successRate: 98,
    avgDuration: "1m 24s",
    outputLabel: "risk reviews",
  },
  {
    key: "delivery",
    name: "Delivery Agent",
    purpose: "Prepares preview messages, website summaries, revision request instructions, and next steps.",
    status: "Idle",
    model: "gpt-4.1-mini",
    lastRun: "2026-06-23T16:44:00.000Z",
    successRate: 90,
    avgDuration: "33s",
    outputLabel: "delivery packets",
  },
];

export const leads: Lead[] = [
  {
    id: "lead-001",
    businessName: "Crown & Fade Barber Studio",
    industry: "Barber shop",
    city: "Hamilton, ON",
    websiteUrl: null,
    email: "owner@crownfade.example",
    phone: "+1 289-555-0101",
    socialLinks: ["instagram.com/crownfade"],
    currentWebsiteQualityScore: 12,
    googlePresenceScore: 74,
    leadScore: 94,
    status: "Interested",
    notes: "Owner replied asking about a booking-first site and price range.",
    source: "Mock generated - Google Maps style batch",
    lastContacted: "2026-06-24T14:35:00.000Z",
    nextFollowUpDate: "2026-06-25T15:00:00.000Z",
    complianceStatus: "Approved",
    estimatedValue: 4200,
    owner: "Mina Torres",
  },
  {
    id: "lead-002",
    businessName: "Northline Dental Care",
    industry: "Dentist",
    city: "Mississauga, ON",
    websiteUrl: "https://northlinedental.example",
    email: "hello@northlinedental.example",
    phone: "+1 905-555-0112",
    socialLinks: ["facebook.com/northlinedental"],
    currentWebsiteQualityScore: 48,
    googlePresenceScore: 82,
    leadScore: 86,
    status: "Owner Talking",
    notes: "Needs a calmer look, insurance information, and new patient CTA.",
    source: "Manual import",
    lastContacted: "2026-06-24T13:18:00.000Z",
    nextFollowUpDate: "2026-06-24T20:30:00.000Z",
    complianceStatus: "Approved",
    estimatedValue: 7800,
    owner: "Dr. Priya Shah",
  },
  {
    id: "lead-003",
    businessName: "Juniper Table Bistro",
    industry: "Restaurant",
    city: "Burlington, ON",
    websiteUrl: "https://junipertable.example",
    email: "events@junipertable.example",
    phone: "+1 905-555-0144",
    socialLinks: ["instagram.com/junipertable", "facebook.com/junipertable"],
    currentWebsiteQualityScore: 35,
    googlePresenceScore: 79,
    leadScore: 81,
    status: "Outreach Sent",
    notes: "Old menu PDF, no online reservations, slow mobile site.",
    source: "Local restaurant list",
    lastContacted: "2026-06-24T11:05:00.000Z",
    nextFollowUpDate: "2026-06-27T15:00:00.000Z",
    complianceStatus: "Approved",
    estimatedValue: 5300,
    owner: "Evan Bouchard",
  },
  {
    id: "lead-004",
    businessName: "SparkleShift Cleaning Co.",
    industry: "Cleaning company",
    city: "Toronto, ON",
    websiteUrl: null,
    email: "book@sparkleshift.example",
    phone: "+1 416-555-0120",
    socialLinks: ["instagram.com/sparkleshiftclean"],
    currentWebsiteQualityScore: 8,
    googlePresenceScore: 57,
    leadScore: 89,
    status: "Send to Website Team",
    notes: "Owner approved a three-page site. Wants quote form and commercial cleaning page.",
    source: "Mock generated - service businesses",
    lastContacted: "2026-06-24T15:44:00.000Z",
    nextFollowUpDate: null,
    complianceStatus: "Approved",
    estimatedValue: 3900,
    owner: "Alina Ruiz",
  },
  {
    id: "lead-005",
    businessName: "Cedar Key Realty",
    industry: "Real estate agent",
    city: "Oakville, ON",
    websiteUrl: "https://cedarkeyrealty.example",
    email: "marco@cedarkeyrealty.example",
    phone: "+1 905-555-0138",
    socialLinks: ["linkedin.com/in/marcocedar", "instagram.com/cedarkeyhomes"],
    currentWebsiteQualityScore: 52,
    googlePresenceScore: 61,
    leadScore: 72,
    status: "Compliance Review",
    notes: "Homepage includes ranking claim that needs evidence before delivery.",
    source: "Manual import",
    lastContacted: "2026-06-22T18:21:00.000Z",
    nextFollowUpDate: "2026-06-25T16:00:00.000Z",
    complianceStatus: "Blocked",
    estimatedValue: 6600,
    owner: "Marco Chen",
  },
  {
    id: "lead-006",
    businessName: "TorqueLab Auto Repair",
    industry: "Mechanic",
    city: "London, ON",
    websiteUrl: "https://torquelabauto.example",
    email: "service@torquelabauto.example",
    phone: "+1 519-555-0180",
    socialLinks: ["facebook.com/torquelab"],
    currentWebsiteQualityScore: 27,
    googlePresenceScore: 88,
    leadScore: 91,
    status: "Website In Progress",
    notes: "Needs service pages, quote request, and fleet maintenance landing page.",
    source: "Mock generated - auto category",
    lastContacted: "2026-06-23T19:11:00.000Z",
    nextFollowUpDate: null,
    complianceStatus: "Approved",
    estimatedValue: 6100,
    owner: "Devon Reed",
  },
  {
    id: "lead-007",
    businessName: "PulseCraft Fitness",
    industry: "Gym",
    city: "Kitchener, ON",
    websiteUrl: "https://pulsecraftfit.example",
    email: "train@pulsecraftfit.example",
    phone: "+1 548-555-0177",
    socialLinks: ["instagram.com/pulsecraftfit", "tiktok.com/@pulsecraftfit"],
    currentWebsiteQualityScore: 44,
    googlePresenceScore: 69,
    leadScore: 79,
    status: "QA Review",
    notes: "Membership CTA and class schedule need mobile QA.",
    source: "Referral list",
    lastContacted: "2026-06-22T17:10:00.000Z",
    nextFollowUpDate: "2026-06-26T13:30:00.000Z",
    complianceStatus: "Pending",
    estimatedValue: 5800,
    owner: "Jordan Miles",
  },
  {
    id: "lead-008",
    businessName: "Luna Glow Beauty Lounge",
    industry: "Beauty salon",
    city: "Vaughan, ON",
    websiteUrl: null,
    email: "hello@lunaglow.example",
    phone: "+1 647-555-0190",
    socialLinks: ["instagram.com/lunaglowlounge"],
    currentWebsiteQualityScore: 10,
    googlePresenceScore: 63,
    leadScore: 87,
    status: "Client Preview Ready",
    notes: "Preview packet needs final owner approval.",
    source: "Instagram prospecting",
    lastContacted: "2026-06-23T20:12:00.000Z",
    nextFollowUpDate: "2026-06-24T22:00:00.000Z",
    complianceStatus: "Approved",
    estimatedValue: 4700,
    owner: "Bianca Moretti",
  },
  {
    id: "lead-009",
    businessName: "BrightPath Tutoring Center",
    industry: "Tutoring center",
    city: "Markham, ON",
    websiteUrl: "https://brightpathtutors.example",
    email: "info@brightpathtutors.example",
    phone: "+1 365-555-0165",
    socialLinks: ["facebook.com/brightpathtutoring"],
    currentWebsiteQualityScore: 39,
    googlePresenceScore: 72,
    leadScore: 76,
    status: "Replied",
    notes: "Asked whether content can be rewritten for summer enrollment.",
    source: "CSV import",
    lastContacted: "2026-06-23T13:00:00.000Z",
    nextFollowUpDate: "2026-06-25T18:00:00.000Z",
    complianceStatus: "Approved",
    estimatedValue: 5200,
    owner: "Sofia Patel",
  },
  {
    id: "lead-010",
    businessName: "Evergreen Edge Landscaping",
    industry: "Landscaping company",
    city: "Guelph, ON",
    websiteUrl: "https://evergreenedge.example",
    email: "quotes@evergreenedge.example",
    phone: "+1 226-555-0151",
    socialLinks: ["instagram.com/evergreenedge"],
    currentWebsiteQualityScore: 31,
    googlePresenceScore: 84,
    leadScore: 90,
    status: "Outreach Ready",
    notes: "High-intent seasonal business, old gallery and weak quote flow.",
    source: "Mock generated - seasonal services",
    lastContacted: null,
    nextFollowUpDate: "2026-06-24T21:00:00.000Z",
    complianceStatus: "Pending",
    estimatedValue: 5600,
    owner: "Nolan Peters",
  },
  {
    id: "lead-011",
    businessName: "Stonebridge Family Dental",
    industry: "Dentist",
    city: "Waterloo, ON",
    websiteUrl: "https://stonebridgefamilydental.example",
    email: "care@stonebridgefamilydental.example",
    phone: "+1 519-555-0126",
    socialLinks: ["facebook.com/stonebridgedental"],
    currentWebsiteQualityScore: 58,
    googlePresenceScore: 76,
    leadScore: 69,
    status: "Scored",
    notes: "Needs conversion polish but site is not broken.",
    source: "Google business profile batch",
    lastContacted: null,
    nextFollowUpDate: null,
    complianceStatus: "Pending",
    estimatedValue: 6900,
    owner: "Dr. Lena Fox",
  },
  {
    id: "lead-012",
    businessName: "Blue Apron Diner",
    industry: "Restaurant",
    city: "Niagara Falls, ON",
    websiteUrl: null,
    email: "blueapronowners@example",
    phone: "+1 289-555-0188",
    socialLinks: ["facebook.com/blueaprondiner"],
    currentWebsiteQualityScore: 5,
    googlePresenceScore: 80,
    leadScore: 88,
    status: "Outreach Ready",
    notes: "No site, strong reviews, menu only exists on social posts.",
    source: "Mock generated - restaurants",
    lastContacted: null,
    nextFollowUpDate: "2026-06-25T14:00:00.000Z",
    complianceStatus: "Approved",
    estimatedValue: 4400,
    owner: "Camila Ortiz",
  },
  {
    id: "lead-013",
    businessName: "West Park Auto Clinic",
    industry: "Mechanic",
    city: "Brampton, ON",
    websiteUrl: "https://westparkauto.example",
    email: "westparkauto@example",
    phone: "+1 905-555-0198",
    socialLinks: ["facebook.com/westparkauto"],
    currentWebsiteQualityScore: 22,
    googlePresenceScore: 67,
    leadScore: 78,
    status: "New",
    notes: "Site still uses a non-secure form and tiny mobile text.",
    source: "Mock generated - automotive",
    lastContacted: null,
    nextFollowUpDate: null,
    complianceStatus: "Pending",
    estimatedValue: 4900,
    owner: "Andre Cole",
  },
  {
    id: "lead-014",
    businessName: "Atlas Home Cleaning",
    industry: "Cleaning company",
    city: "Etobicoke, ON",
    websiteUrl: "https://atlashomecleaning.example",
    email: "hello@atlashomecleaning.example",
    phone: "+1 437-555-0145",
    socialLinks: ["instagram.com/atlashomecleaning"],
    currentWebsiteQualityScore: 46,
    googlePresenceScore: 58,
    leadScore: 70,
    status: "Outreach Sent",
    notes: "Generic template, no instant quote form.",
    source: "CSV import",
    lastContacted: "2026-06-22T16:15:00.000Z",
    nextFollowUpDate: "2026-06-26T16:00:00.000Z",
    complianceStatus: "Approved",
    estimatedValue: 4300,
    owner: "Nadia West",
  },
  {
    id: "lead-015",
    businessName: "Oak & Iron Gym",
    industry: "Gym",
    city: "Barrie, ON",
    websiteUrl: "https://oakandirongym.example",
    email: "members@oakandirongym.example",
    phone: "+1 705-555-0108",
    socialLinks: ["instagram.com/oakandirongym"],
    currentWebsiteQualityScore: 55,
    googlePresenceScore: 73,
    leadScore: 67,
    status: "Closed Lost",
    notes: "Uses a franchise marketing provider and declined.",
    source: "Manual import",
    lastContacted: "2026-06-20T12:20:00.000Z",
    nextFollowUpDate: null,
    complianceStatus: "Approved",
    estimatedValue: 0,
    owner: "Rob Ellis",
  },
  {
    id: "lead-016",
    businessName: "Moss Lane Landscaping",
    industry: "Landscaping company",
    city: "Milton, ON",
    websiteUrl: "https://mosslane.example",
    email: "hello@mosslane.example",
    phone: "+1 289-555-0129",
    socialLinks: ["instagram.com/mosslanelandscaping"],
    currentWebsiteQualityScore: 18,
    googlePresenceScore: 70,
    leadScore: 84,
    status: "Scored",
    notes: "Gallery is strong but website is outdated and slow.",
    source: "Google business profile batch",
    lastContacted: null,
    nextFollowUpDate: null,
    complianceStatus: "Pending",
    estimatedValue: 5100,
    owner: "Theo Walsh",
  },
  {
    id: "lead-017",
    businessName: "Velvet Nail Studio",
    industry: "Beauty salon",
    city: "Richmond Hill, ON",
    websiteUrl: null,
    email: "studio@velvetnails.example",
    phone: "+1 365-555-0119",
    socialLinks: ["instagram.com/velvetnailstudio"],
    currentWebsiteQualityScore: 9,
    googlePresenceScore: 62,
    leadScore: 85,
    status: "New",
    notes: "Booking currently happens through DMs only.",
    source: "Instagram prospecting",
    lastContacted: null,
    nextFollowUpDate: null,
    complianceStatus: "Pending",
    estimatedValue: 3800,
    owner: "Hana Lee",
  },
  {
    id: "lead-018",
    businessName: "Summit Prep Tutors",
    industry: "Tutoring center",
    city: "Toronto, ON",
    websiteUrl: "https://summitpreptutors.example",
    email: "admissions@summitpreptutors.example",
    phone: "+1 416-555-0107",
    socialLinks: ["linkedin.com/company/summitprep"],
    currentWebsiteQualityScore: 63,
    googlePresenceScore: 54,
    leadScore: 64,
    status: "Outreach Sent",
    notes: "Opportunity is SEO/local landing pages more than full rebuild.",
    source: "Manual import",
    lastContacted: "2026-06-21T18:40:00.000Z",
    nextFollowUpDate: "2026-06-25T19:00:00.000Z",
    complianceStatus: "Approved",
    estimatedValue: 4700,
    owner: "Rachel Kim",
  },
  {
    id: "lead-019",
    businessName: "Harbourline Realty Group",
    industry: "Real estate agent",
    city: "Toronto, ON",
    websiteUrl: "https://harbourlinerealty.example",
    email: "team@harbourlinerealty.example",
    phone: "+1 647-555-0158",
    socialLinks: ["instagram.com/harbourlinerealty", "linkedin.com/company/harbourline"],
    currentWebsiteQualityScore: 41,
    googlePresenceScore: 66,
    leadScore: 74,
    status: "Replied",
    notes: "Asked whether IDX can be added later.",
    source: "LinkedIn search",
    lastContacted: "2026-06-23T15:30:00.000Z",
    nextFollowUpDate: "2026-06-24T22:30:00.000Z",
    complianceStatus: "Approved",
    estimatedValue: 7200,
    owner: "Isabel Grant",
  },
  {
    id: "lead-020",
    businessName: "Pine & Pepper Kitchen",
    industry: "Restaurant",
    city: "Cambridge, ON",
    websiteUrl: "https://pinepepper.example",
    email: "hello@pinepepper.example",
    phone: "+1 519-555-0116",
    socialLinks: ["instagram.com/pinepepperkitchen"],
    currentWebsiteQualityScore: 28,
    googlePresenceScore: 77,
    leadScore: 80,
    status: "Outreach Ready",
    notes: "Online ordering link is buried and menu is outdated.",
    source: "Mock generated - restaurants",
    lastContacted: null,
    nextFollowUpDate: "2026-06-25T13:00:00.000Z",
    complianceStatus: "Needs Fixes",
    estimatedValue: 4800,
    owner: "Miles Nguyen",
  },
  {
    id: "lead-021",
    businessName: "Riverbend Physio & Wellness",
    industry: "Health clinic",
    city: "Waterdown, ON",
    websiteUrl: "https://riverbendphysio.example",
    email: "care@riverbendphysio.example",
    phone: "+1 289-555-0172",
    socialLinks: ["facebook.com/riverbendphysio"],
    currentWebsiteQualityScore: 50,
    googlePresenceScore: 71,
    leadScore: 73,
    status: "Scored",
    notes: "Medical-adjacent content requires careful claims review.",
    source: "Manual import",
    lastContacted: null,
    nextFollowUpDate: null,
    complianceStatus: "Pending",
    estimatedValue: 7400,
    owner: "Dr. Maya Singh",
  },
  {
    id: "lead-022",
    businessName: "Silverline Mobile Detailing",
    industry: "Auto detailing",
    city: "Pickering, ON",
    websiteUrl: null,
    email: "book@silverlinedetail.example",
    phone: "+1 905-555-0109",
    socialLinks: ["instagram.com/silverlinedetail"],
    currentWebsiteQualityScore: 6,
    googlePresenceScore: 59,
    leadScore: 82,
    status: "New",
    notes: "No site, strong before-and-after content on Instagram.",
    source: "Mock generated - auto services",
    lastContacted: null,
    nextFollowUpDate: null,
    complianceStatus: "Pending",
    estimatedValue: 3600,
    owner: "Chris Nolan",
  },
  {
    id: "lead-023",
    businessName: "Little Maple Daycare",
    industry: "Childcare",
    city: "Whitby, ON",
    websiteUrl: "https://littlemapledaycare.example",
    email: "admin@littlemapledaycare.example",
    phone: "+1 905-555-0134",
    socialLinks: ["facebook.com/littlemapledaycare"],
    currentWebsiteQualityScore: 34,
    googlePresenceScore: 68,
    leadScore: 77,
    status: "Compliance Review",
    notes: "Privacy and child-photo handling needs careful review.",
    source: "CSV import",
    lastContacted: "2026-06-22T13:25:00.000Z",
    nextFollowUpDate: "2026-06-25T17:00:00.000Z",
    complianceStatus: "Needs Fixes",
    estimatedValue: 6200,
    owner: "Erin Walsh",
  },
  {
    id: "lead-024",
    businessName: "Maple & Main Florals",
    industry: "Florist",
    city: "Hamilton, ON",
    websiteUrl: "https://maplemainflorals.example",
    email: "orders@maplemainflorals.example",
    phone: "+1 289-555-0162",
    socialLinks: ["instagram.com/maplemainflorals"],
    currentWebsiteQualityScore: 43,
    googlePresenceScore: 75,
    leadScore: 71,
    status: "Closed Won",
    notes: "Deposit received, delivery message sent.",
    source: "Referral",
    lastContacted: "2026-06-23T21:15:00.000Z",
    nextFollowUpDate: null,
    complianceStatus: "Approved",
    estimatedValue: 4500,
    owner: "Ava Martin",
  },
  {
    id: "lead-025",
    businessName: "PrimeLock Locksmiths",
    industry: "Locksmith",
    city: "Scarborough, ON",
    websiteUrl: "https://primelock.example",
    email: "dispatch@primelock.example",
    phone: "+1 416-555-0199",
    socialLinks: ["facebook.com/primelock"],
    currentWebsiteQualityScore: 24,
    googlePresenceScore: 83,
    leadScore: 92,
    status: "Outreach Ready",
    notes: "Emergency service pages are thin. High-intent search opportunity.",
    source: "Mock generated - urgent services",
    lastContacted: null,
    nextFollowUpDate: "2026-06-24T23:00:00.000Z",
    complianceStatus: "Approved",
    estimatedValue: 5900,
    owner: "Jon Becker",
  },
];

export const agentRuns: AgentRun[] = [
  {
    id: "run-001",
    agentKey: "security-compliance",
    agentName: "Security & Compliance Agent",
    leadId: "lead-005",
    leadName: "Cedar Key Realty",
    status: "blocked",
    startedAt: "2026-06-24T16:18:00.000Z",
    completedAt: "2026-06-24T16:20:00.000Z",
    summary: "Blocked delivery because the draft made unsupported top-agent and guaranteed-sale claims.",
    riskLevel: "High",
    costEstimate: 0.09,
  },
  {
    id: "run-002",
    agentKey: "website-builder-2",
    agentName: "Website Builder Agent 2",
    leadId: "lead-006",
    leadName: "TorqueLab Auto Repair",
    status: "running",
    startedAt: "2026-06-24T16:46:00.000Z",
    summary: "Drafting service, fleet maintenance, FAQ, and contact pages.",
    riskLevel: "Low",
    costEstimate: 0.14,
  },
  {
    id: "run-003",
    agentKey: "lead-scoring",
    agentName: "Lead Scoring Agent",
    leadId: "lead-025",
    leadName: "PrimeLock Locksmiths",
    status: "completed",
    startedAt: "2026-06-24T16:30:00.000Z",
    completedAt: "2026-06-24T16:32:00.000Z",
    summary: "Scored 92 due to urgent-intent category, weak service pages, and strong Google signal.",
    riskLevel: "Low",
    costEstimate: 0.03,
  },
  {
    id: "run-004",
    agentKey: "outreach",
    agentName: "Outreach Agent",
    leadId: "lead-020",
    leadName: "Pine & Pepper Kitchen",
    status: "completed",
    startedAt: "2026-06-24T16:08:00.000Z",
    completedAt: "2026-06-24T16:10:00.000Z",
    summary: "Generated email, SMS, two follow-ups, and short DM. Compliance flagged one wording fix.",
    riskLevel: "Medium",
    costEstimate: 0.05,
  },
  {
    id: "run-005",
    agentKey: "reply-classifier",
    agentName: "Reply Classifier Agent",
    leadId: "lead-001",
    leadName: "Crown & Fade Barber Studio",
    status: "completed",
    startedAt: "2026-06-24T14:27:00.000Z",
    completedAt: "2026-06-24T14:28:00.000Z",
    summary: "Classified reply as Interested with 94% confidence.",
    riskLevel: "Low",
    costEstimate: 0.01,
  },
  {
    id: "run-006",
    agentKey: "website-intake",
    agentName: "Website Intake Agent",
    leadId: "lead-004",
    leadName: "SparkleShift Cleaning Co.",
    status: "completed",
    startedAt: "2026-06-24T15:44:00.000Z",
    completedAt: "2026-06-24T15:45:00.000Z",
    summary: "Converted owner notes into a three-page commercial cleaning scope with missing photo checklist.",
    riskLevel: "Low",
    costEstimate: 0.04,
  },
  {
    id: "run-007",
    agentKey: "qa",
    agentName: "QA Agent",
    leadId: "lead-007",
    leadName: "PulseCraft Fitness",
    status: "completed",
    startedAt: "2026-06-24T12:40:00.000Z",
    completedAt: "2026-06-24T12:42:00.000Z",
    summary: "Found mobile schedule overflow, one missing CTA, and two low-contrast labels.",
    riskLevel: "Medium",
    costEstimate: 0.04,
  },
  {
    id: "run-008",
    agentKey: "delivery",
    agentName: "Delivery Agent",
    leadId: "lead-008",
    leadName: "Luna Glow Beauty Lounge",
    status: "queued",
    startedAt: "2026-06-24T17:10:00.000Z",
    summary: "Waiting for owner approval before preview packet is prepared.",
    riskLevel: "Low",
    costEstimate: 0,
  },
  {
    id: "run-009",
    agentKey: "marketing-strategy",
    agentName: "Marketing Strategy Agent",
    leadId: "lead-010",
    leadName: "Evergreen Edge Landscaping",
    status: "completed",
    startedAt: "2026-06-24T15:53:00.000Z",
    completedAt: "2026-06-24T15:55:00.000Z",
    summary: "Recommended quote-first spring cleanup and commercial maintenance package angle.",
    riskLevel: "Low",
    costEstimate: 0.06,
  },
  {
    id: "run-010",
    agentKey: "lead-finder",
    agentName: "Lead Finder Agent",
    status: "completed",
    startedAt: "2026-06-24T13:02:00.000Z",
    completedAt: "2026-06-24T13:05:00.000Z",
    summary: "Imported 25 local service businesses and tagged priority verticals.",
    riskLevel: "Low",
    costEstimate: 0.02,
  },
];

export const outreachMessages: OutreachMessage[] = [
  {
    id: "msg-001",
    leadId: "lead-010",
    leadName: "Evergreen Edge Landscaping",
    channel: "Email",
    subject: "Quick idea for more quote requests this season",
    body: "Hi Nolan, I noticed your landscaping work has strong local visibility, but the quote flow could be easier on mobile. We build focused sites for service businesses that make estimate requests clearer and faster. If useful, I can send a short example. AgencyForge AI, Toronto. Reply stop to opt out.",
    status: "Approved",
    complianceStatus: "Approved",
    scheduledFor: "2026-06-24T21:00:00.000Z",
    sentAt: null,
  },
  {
    id: "msg-002",
    leadId: "lead-020",
    leadName: "Pine & Pepper Kitchen",
    channel: "SMS",
    body: "Hi Miles, this is AgencyForge AI. I had a quick website idea that could make menu updates and online ordering easier for Pine & Pepper Kitchen. Want me to send it over? Reply stop to opt out.",
    status: "Draft",
    complianceStatus: "Needs Fixes",
    scheduledFor: "2026-06-25T13:00:00.000Z",
    sentAt: null,
  },
  {
    id: "msg-003",
    leadId: "lead-003",
    leadName: "Juniper Table Bistro",
    channel: "Email",
    subject: "Juniper Table mobile menu idea",
    body: "Hi Evan, I noticed the menu experience is harder than it needs to be on mobile. We help restaurants turn menus, reservations, private dining, and events into a clean conversion path. Happy to share a concise concept. AgencyForge AI. Unsubscribe by replying stop.",
    status: "Sent",
    complianceStatus: "Approved",
    scheduledFor: "2026-06-24T11:05:00.000Z",
    sentAt: "2026-06-24T11:05:00.000Z",
  },
  {
    id: "msg-004",
    leadId: "lead-014",
    leadName: "Atlas Home Cleaning",
    channel: "Email",
    subject: "Cleaning quote form improvement",
    body: "Hi Nadia, I saw Atlas Home Cleaning has a clear service offer, but visitors need a faster way to request a quote. We create booking and quote-focused pages for local service companies. AgencyForge AI. Reply stop to opt out.",
    status: "Sent",
    complianceStatus: "Approved",
    scheduledFor: "2026-06-22T16:15:00.000Z",
    sentAt: "2026-06-22T16:15:00.000Z",
  },
  {
    id: "msg-005",
    leadId: "lead-012",
    leadName: "Blue Apron Diner",
    channel: "DM",
    body: "Your reviews are strong. A simple site with menu, hours, photos, and directions could make it easier for new guests to choose you. AgencyForge AI.",
    status: "Approved",
    complianceStatus: "Approved",
    scheduledFor: "2026-06-25T14:00:00.000Z",
    sentAt: null,
  },
  {
    id: "msg-006",
    leadId: "lead-019",
    leadName: "Harbourline Realty Group",
    channel: "Email",
    subject: "IDX-ready site structure",
    body: "Hi Isabel, I noticed your site could do more with neighborhood pages and buyer/seller paths. We can sketch an IDX-ready structure without making any unsupported market claims. AgencyForge AI. Reply stop to opt out.",
    status: "Sent",
    complianceStatus: "Approved",
    scheduledFor: "2026-06-23T15:30:00.000Z",
    sentAt: "2026-06-23T15:30:00.000Z",
  },
  {
    id: "msg-007",
    leadId: "lead-005",
    leadName: "Cedar Key Realty",
    channel: "Email",
    subject: "Preview delivery blocked",
    body: "Draft currently contains unsupported ranking language and must be revised before it can be sent.",
    status: "Blocked",
    complianceStatus: "Blocked",
    scheduledFor: "2026-06-24T16:45:00.000Z",
    sentAt: null,
  },
  {
    id: "msg-008",
    leadId: "lead-025",
    leadName: "PrimeLock Locksmiths",
    channel: "SMS",
    body: "Hi Jon, this is AgencyForge AI. I noticed emergency locksmith pages often miss fast local service paths. Want a short site improvement idea? Reply stop to opt out.",
    status: "Approved",
    complianceStatus: "Approved",
    scheduledFor: "2026-06-24T23:00:00.000Z",
    sentAt: null,
  },
];

export const replies: Reply[] = [
  {
    id: "reply-001",
    leadId: "lead-001",
    leadName: "Crown & Fade Barber Studio",
    channel: "SMS",
    message: "Yeah send the example. We need online booking to look better.",
    classification: "Interested",
    receivedAt: "2026-06-24T14:26:00.000Z",
    confidence: 94,
  },
  {
    id: "reply-002",
    leadId: "lead-009",
    leadName: "BrightPath Tutoring Center",
    channel: "Email",
    message: "Could this help with summer enrollment pages? Please send more info.",
    classification: "Needs more info",
    receivedAt: "2026-06-23T13:41:00.000Z",
    confidence: 89,
  },
  {
    id: "reply-003",
    leadId: "lead-019",
    leadName: "Harbourline Realty Group",
    channel: "Email",
    message: "Can IDX be integrated later or would this only be a brochure site?",
    classification: "Needs more info",
    receivedAt: "2026-06-23T18:58:00.000Z",
    confidence: 86,
  },
  {
    id: "reply-004",
    leadId: "lead-002",
    leadName: "Northline Dental Care",
    channel: "Email",
    message: "Can we book a call today? We want to update the new patient pages.",
    classification: "Call requested",
    receivedAt: "2026-06-24T12:04:00.000Z",
    confidence: 96,
  },
  {
    id: "reply-005",
    leadId: "lead-015",
    leadName: "Oak & Iron Gym",
    channel: "Email",
    message: "No thanks, our franchise provider handles this.",
    classification: "Not interested",
    receivedAt: "2026-06-20T12:14:00.000Z",
    confidence: 98,
  },
];

export const websiteProjects: WebsiteProject[] = [
  {
    id: "web-001",
    leadId: "lead-006",
    leadName: "TorqueLab Auto Repair",
    industry: "Mechanic",
    packageName: "Growth Website + Local SEO",
    status: "In Progress",
    progress: 64,
    brandStyle: "Industrial, clean, high-trust, service-first.",
    primaryGoal: "Increase repair quote requests and fleet maintenance inquiries.",
    previewUrl: "/websites/torquelab-preview",
    estimatedRevenue: 6100,
    updatedAt: "2026-06-24T16:46:00.000Z",
    pages: [
      {
        id: "page-001",
        pageName: "Home",
        slug: "/",
        status: "Ready for QA",
        seoTitle: "Auto Repair in London, ON | TorqueLab Auto Repair",
        sections: [
          {
            id: "section-001",
            type: "hero",
            title: "Reliable repairs without the shop-floor confusion",
            copy: "A clear service path for drivers and fleet managers who need diagnostics, maintenance, and transparent estimates.",
            cta: "Request a repair estimate",
          },
          {
            id: "section-002",
            type: "services",
            title: "Repairs, diagnostics, and fleet maintenance",
            copy: "Service cards for brakes, diagnostics, oil changes, tires, inspections, and fleet service contracts.",
          },
          {
            id: "section-003",
            type: "proof",
            title: "Built around local trust",
            copy: "Google review highlights, warranty language, technician credentials, and transparent process copy.",
          },
        ],
      },
      {
        id: "page-002",
        pageName: "Services",
        slug: "/services",
        status: "Draft",
        seoTitle: "Auto Repair Services | TorqueLab Auto Repair",
        sections: [
          {
            id: "section-004",
            type: "content",
            title: "Service pages structured for high-intent searches",
            copy: "Dedicated sections for diagnostic checks, brake service, fleet repair, seasonal maintenance, and emergency repair requests.",
          },
        ],
      },
    ],
  },
  {
    id: "web-002",
    leadId: "lead-007",
    leadName: "PulseCraft Fitness",
    industry: "Gym",
    packageName: "Membership Conversion Site",
    status: "QA Review",
    progress: 82,
    brandStyle: "Energetic but premium, black-and-silver fitness editorial.",
    primaryGoal: "Convert class schedule visitors into trial pass signups.",
    previewUrl: "/websites/pulsecraft-preview",
    estimatedRevenue: 5800,
    updatedAt: "2026-06-24T12:42:00.000Z",
    pages: [
      {
        id: "page-003",
        pageName: "Home",
        slug: "/",
        status: "QA Review",
        seoTitle: "Personal Training and Classes in Kitchener | PulseCraft Fitness",
        sections: [
          {
            id: "section-005",
            type: "hero",
            title: "Training plans built around real schedules",
            copy: "A gym homepage with a trial-pass CTA, class highlights, coach proof, and membership pathways.",
            cta: "Claim a trial pass",
          },
          {
            id: "section-006",
            type: "process",
            title: "From trial to member",
            copy: "Book a trial, meet a coach, choose a plan, and track progress.",
          },
        ],
      },
    ],
  },
  {
    id: "web-003",
    leadId: "lead-008",
    leadName: "Luna Glow Beauty Lounge",
    industry: "Beauty salon",
    packageName: "Booking-First Beauty Site",
    status: "Client Preview Ready",
    progress: 96,
    brandStyle: "Soft luxury, champagne accents, editorial service photography.",
    primaryGoal: "Move Instagram interest into direct bookings.",
    previewUrl: "/websites/lunaglow-preview",
    estimatedRevenue: 4700,
    updatedAt: "2026-06-23T20:12:00.000Z",
    pages: [
      {
        id: "page-004",
        pageName: "Home",
        slug: "/",
        status: "Client Preview Ready",
        seoTitle: "Beauty Lounge in Vaughan | Luna Glow",
        sections: [
          {
            id: "section-007",
            type: "hero",
            title: "A polished beauty experience from first click to appointment",
            copy: "Service-led homepage with booking CTA, social proof, package cards, and care instructions.",
            cta: "Book your appointment",
          },
          {
            id: "section-008",
            type: "faq",
            title: "Common booking questions",
            copy: "Deposit, cancellation, prep, aftercare, and service duration answers.",
          },
        ],
      },
    ],
  },
  {
    id: "web-004",
    leadId: "lead-004",
    leadName: "SparkleShift Cleaning Co.",
    industry: "Cleaning company",
    packageName: "Commercial Lead Capture Site",
    status: "Intake",
    progress: 24,
    brandStyle: "Fresh, precise, bright but professional.",
    primaryGoal: "Generate commercial cleaning quote requests.",
    previewUrl: "/websites/sparkleshift-preview",
    estimatedRevenue: 3900,
    updatedAt: "2026-06-24T15:45:00.000Z",
    pages: [
      {
        id: "page-005",
        pageName: "Home",
        slug: "/",
        status: "Draft",
        seoTitle: "Commercial Cleaning Services in Toronto | SparkleShift",
        sections: [
          {
            id: "section-009",
            type: "hero",
            title: "Clean workspaces without quote-request friction",
            copy: "A three-page site plan focused on recurring office cleaning, move-out cleans, and fast quote capture.",
            cta: "Request a cleaning quote",
          },
        ],
      },
    ],
  },
];

export const complianceReviews: ComplianceReview[] = [
  {
    id: "comp-001",
    targetType: "Website Content",
    targetName: "Cedar Key Realty preview",
    leadId: "lead-005",
    riskLevel: "High",
    issuesFound: ["Unsupported claim: top-ranked agent", "Guarantee language implies certain sale outcome"],
    fixesRequired: ["Replace ranking claim with verifiable proof", "Remove guarantee or add accurate qualifying language"],
    status: "Blocked",
    timestamp: "2026-06-24T16:20:00.000Z",
    agentNotes: "Delivery must remain blocked until claims are rewritten and reviewed.",
  },
  {
    id: "comp-002",
    targetType: "Outreach",
    targetName: "Pine & Pepper Kitchen SMS",
    leadId: "lead-020",
    riskLevel: "Medium",
    issuesFound: ["Sender identity present but opt-out wording should be clearer"],
    fixesRequired: ["Use explicit stop/opt-out line", "Avoid implying existing relationship"],
    status: "Needs Fixes",
    timestamp: "2026-06-24T16:11:00.000Z",
    agentNotes: "Can be approved after small wording fix.",
  },
  {
    id: "comp-003",
    targetType: "Contact Form",
    targetName: "TorqueLab estimate form",
    leadId: "lead-006",
    riskLevel: "Low",
    issuesFound: ["Collects name, phone, email, vehicle issue"],
    fixesRequired: ["Add privacy note beside form", "Store submissions server-side only"],
    status: "Approved",
    timestamp: "2026-06-24T15:18:00.000Z",
    agentNotes: "Low risk with privacy note included.",
  },
  {
    id: "comp-004",
    targetType: "Outreach",
    targetName: "Evergreen Edge first email",
    leadId: "lead-010",
    riskLevel: "Low",
    issuesFound: ["No misleading claims found", "Unsubscribe line included"],
    fixesRequired: [],
    status: "Approved",
    timestamp: "2026-06-24T15:58:00.000Z",
    agentNotes: "CASL-style basics satisfied for the demo dataset.",
  },
  {
    id: "comp-005",
    targetType: "Privacy",
    targetName: "Little Maple Daycare site plan",
    leadId: "lead-023",
    riskLevel: "Medium",
    issuesFound: ["Childcare content may use child photos", "Contact form collects parent and child program interest"],
    fixesRequired: ["Confirm image permissions", "Add privacy policy before delivery", "Avoid displaying child names"],
    status: "Needs Fixes",
    timestamp: "2026-06-23T20:16:00.000Z",
    agentNotes: "Privacy policy and image permissions are required before preview.",
  },
  {
    id: "comp-006",
    targetType: "Delivery",
    targetName: "Luna Glow preview packet",
    leadId: "lead-008",
    riskLevel: "Low",
    issuesFound: ["No high-risk claims", "No analytics cookie notice needed in static preview"],
    fixesRequired: ["Keep booking form privacy note in final handoff"],
    status: "Approved",
    timestamp: "2026-06-23T20:45:00.000Z",
    agentNotes: "Ready for owner approval and client preview.",
  },
];

export const tasks: Task[] = [
  {
    id: "task-001",
    title: "Call Northline Dental",
    description: "Owner requested a call today about new patient page priorities.",
    priority: "Critical",
    status: "Open",
    dueAt: "2026-06-24T20:30:00.000Z",
    relatedLead: "Northline Dental Care",
    action: "Open conversation notes",
  },
  {
    id: "task-002",
    title: "Approve Luna Glow preview",
    description: "Compliance is approved. Delivery Agent is waiting for owner approval.",
    priority: "High",
    status: "Open",
    dueAt: "2026-06-24T22:00:00.000Z",
    relatedLead: "Luna Glow Beauty Lounge",
    action: "Prepare delivery packet",
  },
  {
    id: "task-003",
    title: "Fix Cedar Key claims",
    description: "Compliance blocked unsupported ranking and guarantee language.",
    priority: "Critical",
    status: "In Progress",
    dueAt: "2026-06-25T16:00:00.000Z",
    relatedLead: "Cedar Key Realty",
    action: "Open compliance review",
  },
  {
    id: "task-004",
    title: "Send SparkleShift to website agents",
    description: "Owner notes are complete and the lead is ready for intake.",
    priority: "High",
    status: "Open",
    dueAt: "2026-06-24T18:30:00.000Z",
    relatedLead: "SparkleShift Cleaning Co.",
    action: "Send to Website Team",
  },
  {
    id: "task-005",
    title: "Review Pine & Pepper SMS",
    description: "Compliance requires clearer opt-out wording before sending.",
    priority: "Medium",
    status: "Open",
    dueAt: "2026-06-25T13:00:00.000Z",
    relatedLead: "Pine & Pepper Kitchen",
    action: "Edit outreach",
  },
];

export const activityLogs: ActivityLog[] = [
  {
    id: "log-001",
    actor: "Security & Compliance Agent",
    action: "blocked",
    target: "Cedar Key Realty delivery",
    timestamp: "2026-06-24T16:20:00.000Z",
    severity: "critical",
  },
  {
    id: "log-002",
    actor: "Website Builder Agent 2",
    action: "started drafting",
    target: "TorqueLab service pages",
    timestamp: "2026-06-24T16:46:00.000Z",
    severity: "info",
  },
  {
    id: "log-003",
    actor: "Lead Scoring Agent",
    action: "scored 92",
    target: "PrimeLock Locksmiths",
    timestamp: "2026-06-24T16:32:00.000Z",
    severity: "success",
  },
  {
    id: "log-004",
    actor: "Outreach Agent",
    action: "generated compliant set",
    target: "Evergreen Edge Landscaping",
    timestamp: "2026-06-24T15:56:00.000Z",
    severity: "success",
  },
  {
    id: "log-005",
    actor: "Reply Classifier Agent",
    action: "classified reply as interested",
    target: "Crown & Fade Barber Studio",
    timestamp: "2026-06-24T14:28:00.000Z",
    severity: "success",
  },
  {
    id: "log-006",
    actor: "QA Agent",
    action: "found mobile overflow",
    target: "PulseCraft Fitness schedule module",
    timestamp: "2026-06-24T12:42:00.000Z",
    severity: "warning",
  },
  {
    id: "log-007",
    actor: "Lead Finder Agent",
    action: "imported 25 leads",
    target: "Ontario service business batch",
    timestamp: "2026-06-24T13:05:00.000Z",
    severity: "info",
  },
];

export const settings: Settings = {
  agencyName: "AgencyForge AI",
  ownerName: "Idrees",
  senderEmail: "hello@agencyforge.ai",
  senderPhone: "+1 647-555-0191",
  mockMode: true,
  complianceRegion: "Canada",
};

export const funnelData = [
  { name: "Leads", value: leads.length },
  { name: "Scored", value: leads.filter((lead) => lead.leadScore > 0).length },
  { name: "Outreach", value: leads.filter((lead) => ["Outreach Ready", "Outreach Sent", "Replied", "Interested", "Owner Talking"].includes(lead.status)).length },
  { name: "Interested", value: leads.filter((lead) => ["Interested", "Owner Talking", "Send to Website Team"].includes(lead.status)).length },
  { name: "Websites", value: websiteProjects.length },
  { name: "Won", value: leads.filter((lead) => lead.status === "Closed Won").length },
];

export const revenueSeries = [
  { month: "Jan", value: 11800 },
  { month: "Feb", value: 16400 },
  { month: "Mar", value: 22100 },
  { month: "Apr", value: 29800 },
  { month: "May", value: 38200 },
  { month: "Jun", value: leads.reduce((sum, lead) => sum + lead.estimatedValue, 0) },
];

export const agentKeys: AgentKey[] = agentDefinitions.map((agent) => agent.key);
